### ISSUE TITLE
Feature: User can create a project

### ISSUE THREAD

**Issue by parkersiu** [parkersiu/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a project.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can create a new project with a title and description.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-12-29 at 3 05 01 PM](https://user-images.githubusercontent.com/111034849/210019659-85e98034-ab83-443a-95d3-add3528efc50.png)
![Screen Shot 2022-12-29 at 3 08 56 PM](https://user-images.githubusercontent.com/111034849/210019661-c58b342b-f3f7-45bb-a21c-c03a43b2e662.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update schema.sql to reflect database design including the (users, projects, and tasks) tables

### ☁️ Server Tasks

- [x] Update `server/index.js` to query the db and update the projects table with new projects
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to render a navbar
- [x] Create a component to render a breadcrumb
- [x] Create a component to render a form with an input and textarea.

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
