### ISSUE TITLE
Feature: User can set milestones

### ISSUE THREAD

**Issue by parkersiu** [parkersiu/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can set milestones

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can add milestones to a project.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-12-29 at 3 11 14 PM](https://user-images.githubusercontent.com/111034849/210019841-7ead74c1-49a5-4740-8caf-f82748884b48.png)
![Screen Shot 2022-12-29 at 3 11 25 PM](https://user-images.githubusercontent.com/111034849/210019843-84ebf3fc-4f88-47c5-9bc5-3d2a31f1637b.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature

### 🐘 Database Tasks

- [x] Update schema.sql to include a milestones table

### ☁️ Server Tasks

- [x] Update `server/index.js` to handle a post request for adding milestones to the database.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to render a milestone form. The form should start with 3 inputs by default, but add or delete input fields based on user clicks.
- [x] Update handleSubmit to include a addMilestone function and fetch API

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
