### ISSUE TITLE
Feature: User can add tasks to a milestone

### ISSUE THREAD

**Issue by parkersiu** [parkersiu/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add tasks to a milestone

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can add a custom amount of tasks to each milestone in a project

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2023-01-03 at 2 50 06 PM](https://user-images.githubusercontent.com/111034849/210454287-cc8f2765-965f-46d5-82de-62e4b3b74d62.png)
![Screen Shot 2022-12-29 at 3 12 52 PM](https://user-images.githubusercontent.com/111034849/210019935-c41f1bd2-4178-4c9a-bbfb-b6daab1a68fc.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to handle POST request for storing tasks
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to render milestone "cards" and tasks for each card.
- [x] Update page title component to render the project name.

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
